#!/bin/bash
# Aliases for TaskWarrior

# References:
# * https://cs-syd.eu/posts/2015-06-14-gtd-with-taskwarrior-part-1-intro.html
# * https://cs-syd.eu/posts/2015-06-21-gtd-with-taskwarrior-part-2-collection.html
# * https://cs-syd.eu/posts/2015-06-28-gtd-with-taskwarrior-part-3-tickling.html
# * https://cs-syd.eu/posts/2015-07-05-gtd-with-taskwarrior-part-4-processing.html
# * https://cs-syd.eu/posts/2015-07-12-gtd-with-taskwarrior-part-5-doing.html

alias in='task add +in'

# tickle () {
#   if [[ $1 =~ [^0-9] ]]; then
#     local deadline=$1
#     shift
#     task add +in +tickle wait:$deadline $@
#   else
#     task $1 modify +tickle wait:$2
#   fi
# }

# alias tick=tickle
# alias think='tickle +1d'

webpage_title () {
  curl -s "$1" | grep -i '<title>' | head -n1 | sed -e 's/<[^>]*>//g' | tr -d '\r\n'
}

read_and_review (){
  link="$1"
  title=$(webpage_title "$link")
  descr="\"Read and review: $title\""
  id=$(task add +in +rnr "$descr" | sed -n 's/Created task \(.*\)./\1/p')
  task "$id" annotate "$link"
}

inbox() {
  local inbox projects
  local NC="\033[0m"
  local RED="\033[0;31m"
  local GREEN="\033[0;32m"
  local YELLOW="\033[0;33m"
  local IS_OK=0

  inbox=$(task +PENDING +READY +in count)
  projects=$( (task +PROJECT +PENDING +READY -waiting _projects; task +PROJECT +next _projects) | sort | uniq -u )

  if [[ $inbox -gt 0 ]]; then
    echo -e "${YELLOW}You have ${inbox} tasks in the INBOX:${NC}\n"
    task +PENDING +READY +in
    IS_OK=1
  else
    echo -e "${GREEN}No tasks in the INBOX${NC}"
  fi

  if [[ -n $projects ]]; then
    echo -e "\n${RED}Attention: The following projects don't currently have a next action:${NC}\n"
    if [[ "$1" == "-v" ]]; then
      for project in $projects; do
        echo "$project"
        task rc.context=none "pro:$project"
      done
    else
      echo "$projects"
    fi
    IS_OK=1
  fi

  return $IS_OK
}

project_note() {
  local id="$1"
  local dir="$HOME/.task/project_notes"
  local file="$dir/$id.otl"

  if [[ -z $id ]]; then
    echo "Missing project name"
    return 1
  fi

  mkdir -p "$dir"
  ${VISUAL:-${EDITOR:-vi}} "$file"
}

alias rnr=read_and_review
alias n=project_note
alias t=task

# vim: ft=sh ts=2 sw=2 et
