#!/bin/bash
randpass() {
	local trstring="A-Za-z0-9_\!\@\#\$\%\^\&\*\(\)-+="
	if [ "$1" = "-a" ]; then
		trstring="A-Za-z0-9"
		shift
	fi
	printf "%s\n" "$(LC_CTYPE=C tr -dc "$trstring" < /dev/urandom | head -c ${1:-20})"
}

chmod_format() {
	sed 's/.\(.........\).*/\1/
		h;y/rwsxtSTlL-/IIIIIOOOOO/;x;s/..\(.\)..\(.\)..\(.\)/|\1\2\3/
		y/sStTlLx-/IIIIIIOO/;G
		s/\n\(.*\)/\1;OOO0OOI1OIO2OII3IOO4IOI5IIO6III7/;:k
		s/|\(...\)\(.*;.*\1\(.\)\)/\3|\2/;tk
		s/^0*\(..*\)|.*/\1/;q'
}

# A util function to setup missing file paths that some programs and scripts
# expect.
setupTempPaths() {
	mkdir -p ~/tmp/sessions
	touch ~/.tmux.conf.local
	touch ~/.vim/local.vim
	touch ~/.vim/local_gui.vim
	touch ~/.bash_aliases
	if [[ ! -e ~/.bash_modules ]]; then
		cat > ~/.bash_modules <<-"EOF"
			# bash_modules - defines what modules to load into the bash environment
			# Repository at http://github.com/sukima/dotfiles
			# Generated for the first time by repository install.sh.
			#
			# Uncomment any of the following modules to load on next shell invocation.
			EOF
		for p in ~/.homesick/repos/dotfiles/bash/modules.d/*; do
			echo
			egrep "^#[^!][	]*[^	]" $p | head -n1
			echo "# $(basename $p)"
		done >> ~/.bash_modules
	fi
}

fixtty() {
	reset
	stty stop undef
	clear
}

# Convinience method to check if a command exists or not.
command_exists() {
	hash "$1" &> /dev/null
}

# Utility functions to manipulate the PATH.
# Used to prevent duplicates on multiple calls.
inPath() {
	echo "${PATH}" | grep "$1" > /dev/null
}

notInPath() {
	if inPath "$1"; then
		return 1
	else
		return 0
	fi
}

addToPath() {
	if notInPath "$1"; then
		PATH="${PATH}:$1"
	fi
	export PATH
}

prependToPath() {
	if notInPath "$1"; then
		PATH="$1:${PATH}"
	fi
	export PATH
}

# vim: ft=sh sw=2 ts=2 noet fdm=marker
