#!/usr/bin/env node
'use strict';

var http = require('http');
var spawn = require('child_process').spawn;
var SELECTIONS = ['primary', 'secondary', 'clipboard'];

var server = http.createServer(function (req, res) {
  var child;
  var selection = req.url.substr(1).toLowerCase();
  selection = SELECTIONS.some(function (i) { return i === selection; })
    ? selection
    : 'clipboard';
  if (req.method === 'GET') {
    child = spawn('/usr/bin/xclip', ['-o', '-selection', selection]);
    res.writeHead(200, { 'Content-Type': 'application/octet-stream' });
    child.stdout.pipe(res)
  } else if (req.method === 'POST') {
    child  = spawn('/usr/bin/xclip', ['-i', '-selection', selection]);
    res.writeHead(204, { 'Content-Type': 'text/plain' });
    req.pipe(child.stdin);
    req.on('end', function () { res.end(); });
  } else {
    res.writeHead(405, { 'Content-Type': 'text/plain' });
    res.end('Method ' + req.method + ' Not Allowed.');
  }
});

server.listen(32010, function () {
  console.log('Listening on ' + server.address().port);
});
