#!/bin/bash
# Convert file contents to Data URI format

type=$(file --mime-type "$1" | awk -F": " '{print $(NF)}')
cat <(printf "data:${type};base64,") <(base64 -w0 "$1")

# vim:set ft=sh sw=4 et fdm=marker :
