#!/bin/bash
source "$HOME/.homesick/repos/dotfiles/contrib/config-parser.sh"

if [ ! -e "$HOME/.encfstab" ]; then
  echo "~/.encfstab does not exist. Aborting" 1>&2
  exit 2
fi

config_parser "$HOME/.encfstab"

if [ "$1" = "-u" ]; then
  umount=yes
  shift
fi

name="$1"
tagname="$name"
eval "config.section.$tagname" > /dev/null 2>&1
config.section.defaults > /dev/null 2>&1
eval "config.section.$tagname" > /dev/null 2>&1

if [[ $? != 0 ]]; then
  echo "Unknown ~/.encfstab entry $tagname"
  exit 3
fi

if [ -n "$extpass" ]; then
  tmpfile="$(mktemp /tmp/encmount-extpass.XXXX)"
  trap "rm -f '$tmpfile'" EXIT
  echo "#!/bin/bash" > "$tmpfile"
  echo "eval \"exec $extpass\"" >> "$tmpfile"
  chmod 700 "$tmpfile"
  extpassarg="--extpass=\"$tmpfile\""
fi

path="$(eval "cd $path" && pwd)"
mount="$(eval "cd $mount" && pwd)"

if [ "$umount" = "yes" ]; then
  echo umount "$mount"
  umount "$mount"
else
  echo encfs $options "$extpassarg" "$path" "$mount"
  encfs $options "$extpassarg" "$path" "$mount"
fi
