#!/bin/bash
#
# git openlast - look at the changed files in the previous commit and open
# those as tabs in Vim.
#

REF="${1:-HEAD}"

git show --stat "$REF"

files=($(git diff --diff-filter=AM --ignore-submodules --name-only --no-renames "${REF}^..${REF}" | xargs grep -Il ""))

read -p "Open ${#files[@]} files in Vim tabs? (Y/n)" -n 1 -r

if [[ -z $REPLY || $REPLY =~ [Yy] ]]; then
  exec vim -p ${files[@]}
else
  exit 1
fi
