#!/bin/bash

VERSION=1.0
config_file="${HOME}/.pomodororc"
lockdir="${HOME}/.pomodoro"
mode="status"

usage() {
  echo "Usage: pomodoro [-vhspblk] [-c FILE] [--lockdir DIR]"
  echo "Version: $VERSION"
  echo "  -h, --help         This cruft"
  echo "  -v, --version      Print the version"
  echo "  -s, --status       Output status for current running Pomodoro"
  echo "  -p, --pomodoro     Start a Pomodoro"
  echo "  -b, --break        Start a short break"
  echo "  -l, --long-break   Start a long break"
  echo "  -k, --kill         Kill current running Pomodoro"
  echo "  -c, --config FILE  Load config from FILE (default '~/.pomodororc')"
  echo "  --lockdir DIR      Use DIR to save the lockfiles (default '~/.pomodoro')"
}

while test $# -gt 0
do
  case $1 in
  # Normal option processing
    -h | --help)
      usage
      exit 0
      ;;
    -v | --version)
      echo "Version: $VERSION"
      exit 0
      ;;
    -s | --status)
      mode="status"
      ;;
    -p | --pomodoro)
      mode="pomodoro"
      ;;
    -b | --break)
      mode="break"
      ;;
    -l | --long-break)
      mode="longbrake"
      ;;
    -k | --kill)
      mode="kill"
      ;;
    -c | --config)
      shift
      config_file="$1"
      ;;
    --lockdir)
      shift
      lock_dir="$1"
      ;;

  # ...

  # Special cases
    --)
      break
      ;;
    --* | -?)
      echo "pomodoro: unknown option -- $1" >&2
      usage >&2
      exit 1
      ;;

  # Done with options
    *)
      break
      ;;
  esac

  shift
done

echo "config_file: $config_file"
echo "lockdir: $lockdir"
echo "mode: $mode"
