#!/bin/bash

VERSION=1.0
config_file="${HOME}/.pomodororc"
mode_command="status"

usage() {
  echo "Usage: pomodoro [-hvspbl] [-c FILE]"
  echo "Version: $VERSION"
  echo "  -h, --help         This cruft"
  echo "  -v, --version      Print the version"
  echo "  -s, --status       Output status for current running Pomodoro"
  echo "  -p, --pomodoro     Start a Pomodoro"
  echo "  -b, --break        Start a short break"
  echo "  -l, --long-break   Start a long break"
  echo "  -c, --config FILE  Load config from FILE (default '~/.pomodororc')"
}

status() {
  echo "Status command executed"
}

while test $# -gt 0
do
  case $1 in
  # Normal option processing
    -h | --help)
      usage
      exit 0
      ;;
    -v | --version)
      echo "Version: $VERSION"
      exit 0
      ;;
    -s | --status)
      mode_command="status"
      ;;
    -p | --pomodoro)
      mode_command="pomodoro"
      ;;
    -b | --break)
      mode_command="break"
      ;;
    -l | --long-break)
      mode_command="longbrake"
      ;;
    -c | --config)
      shift
      config_file="$1"
      ;;

  # ...

  # Special cases
    --)
      break
      ;;
    --* | -?)
      echo "pomodoro: unknown option -- $1" >&2
      usage >&2
      exit 1
      ;;

  # Done with options
    *)
      break
      ;;
  esac

  shift
done

echo "config_file: $config_file"
echo "mode_command: $mode_command"
$mode_command
