#!/bin/bash

# List from http://stackoverflow.com/a/2205826/227176
# u2013 – en dash
# u2014 — em dash
# u2015 ― horizontal bar
# u2017 ‗ double low line
# u2018 ‘ left single quotation mark
# u2019 ’ right single quotation mark
# u201a ‚ single low-9 quotation mark
# u201b ‛ single high-reversed-9 quotation mark
# u201c “ left double quotation mark
# u201d ” right double quotation mark
# u201e „ double low-9 quotation mark
# u2026 … horizontal ellipsis
# u2032 ′ prime
# u2033 ″ double prime

cat ${1:--} | \
  tr '–—―‗‘’‚‛“”„′″' "---_'',''\"\"\"'\"" | \
  sed 's/…/.../g'
