#!/bin/bash

if [[ -z "$TMUX" ]]; then
  echo "Expected a TMUX session to running" >&2
  exit 1
fi

WINSIZE=6
EMOJI=(
  '¯\_(ツ)_/¯'
  'ಠ_ಠ'
  'ʕ •ᴥ•ʔ'
  'ლ(ಠ益ಠლ)'
  '（^人^）'
  '(ˆڡˆ)v'
  '＼(＾O＾)／'
  '(╥﹏╥)'
  '(╯°□°）╯︵ ┻━┻'
)

if [[ "$1" == "-s" ]]; then
  PS3="(^d to cancel) #?"
  select CHOICE in "${EMOJI[@]}"; do
    tmux send-keys -l -t:.- "$CHOICE"
    exit 0
  done
else
  tmux split-window -v -l $WINSIZE "$0 -s"
fi
