#!/bin/bash
# Check for bash (and that we haven't already been sourced).
[ -z "$BASH_VERSION" -o -n "$BASH_COMPLETION" ] && return

# Check for recent enough version of bash.
bash=${BASH_VERSION%.*}; bmajor=${bash%.*}; bminor=${bash#*.}

# Check for interactive shell.
if [ -n "$PS1" ]; then
	if [ $bmajor -eq 2 -a $bminor '>' 04 ] || [ $bmajor -gt 2 ]; then
		if [ -f /etc/bash_completion ]; then
			. /etc/bash_completion
		fi
		# Homebrew on Mac places completions here (brew install bash-completion)
		if [ -f /usr/local/etc/bash_completion ]; then
			. /usr/local/etc/bash_completion
		fi
	fi
fi
unset bash bminor bmajor

# vim: ft=sh sw=2 ts=2 noet fdm=marker
